# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Product.destroy_all

Product.create! ([
  {name:"All Terrain T/A KO2", brand:"LT245/70R17", itemNum:"BFG-966", desc:"The BFGoodrich All-Terrain T/A KO2 is an all-season/winter all-terrain on-and-off road passenger light truck tire with resilient sidewalls and sturdy construction.  This tire is designed with an innovative tread pattern that resists damage from off-road debris while providing increased traction on gravel, soft soil, or even deep snow.", brandName:"BFGoodrich", price:"218.97", year:"2015", model:"Ford", make: "F-150 XLT H-Duty 4WD"},
  {name:"Dueler H/L Alenza Plus", brand:"245/70R17", itemNum:"BT-438", desc:"The Bridgestone Dueler H/L Alenza Plus is designed to deliver a quiet and comfortable highway ride.  This tire delivers improved fuel efficiency (as compared to the Bridgestone Dueler H/L Alenza), year-around performance, and an 80,000 mile treadwear warranty.", brandName:"Bridgestone", price:"220.30", year:"2017", model:"Jeep", make:"Grand Cherokee Laredo 2WD" },
  {name:"Wrangler DuraTrac", brand:"LT245/70R17/E", itemNum:"312022142", desc:"A workhorse tire for rugged off-road terrain -- including snow -- that still offers a quieter ride on paved roads.  The bold aggressive tread design is great for work truck towing and hauling.", brandName:"Goodyear", price:"216.00", year:"2015", model:"Ford", make:"F-150 XLT H-Duty 4WD"},
  {name:"Savero HT2", brand:"LT245/70R17", itemNum:"GT-1724570GTS", desc:"The new generation Savero HT2 premium all-season tire is for SUV and light truck owners who really enjoy driving; the tire's tread pattern unparalleled handlin and control in wet and dry conditions.", brandName:"GT Radial", price:"123.12", year:"2014", model:"Jeep", make:"Grand Cherokee Laredo 4WD"},
  {name:"Eagle Sport All-Season", brand:"245/45R20", itemNum:"109069366", desc:"A powerful sport performance tire with enhanced responsive handling and strong grip in all-season conditions.", brandName:"Goodyear", price:"185.00", year:"2013", model:"Dodge", make:"Challenger R/T"},
  {name:"Sport Maxx GT", brand:"P245/50R18", itemNum:"265023857", desc:"Ultra high-performance for the uncompromising driver", brandName:"Dunlop SP", price:"354.00", year:"2015", model:"Infiniti", make:"Q70L"},
  {name:"Sport Maxx GT", brand:"P245/50R18", itemNum:"265023857", desc:"Ultra high-performance for the uncompromising driver", brandName:"Dunlop SP", price:"354.00", year:"2017", model:"Infiniti", make:"Q70L"},
  {name:"Wrangler All-Terrain Adventure With Kevlar", brand:"P255/60R19", itemNum:"785083572", desc:"Our best tire for versatility on-and-off road, featuring DuPont Kevlar for rugged strength --plus superior traction through rain and snow.  For both everyday highway driving and going off-road at a moment's notice.", brandName:"Goodyear", price:"230.00", year:"2012", model:"Buick", make:"Enclave Standard"},
  {name:"Latitude X-ice XI2", brand:"245/70R17", itemNum:"MICH-27263", desc:"Maneuver through this winter with ease -- the Michelin Latitude X-Ice Xi2 tire lets you take control of your surroundings. With interlocking sipes (slits in the tire) and micro-pumps, this tire uses all of the technology at its disposal to give you outstanding traction,winter after winter. The incredible Latitude X-Ice Xi2 brings pleasure back into cold-weather driving.", brandName:"Michelin", price:"187.86", year:"2016", model:"Jeep", make:"Cherokee 4WD"},
  {name:"ContiProContact", brand:"255/45R19XL", itemNum:"03500070000", desc:"Don’t let wet weather dampen your mood – this quiet tire delivers exceptional wet performance.", brandName:"Continental", price:"215.99", year:"2019", model:"Toyota", make:"Avalon Limited"},
  {name:"Altimax RT43", brand:"255/45R19XL", itemNum:"15502750000", desc:"With powerful all-season traction, built-in safety features, and a smooth, quiet ride, the General Altimax RT43 has everything you look for in a touring tire – and then some. This tire is packed with smart monitoring technology that helps keep you safe on the road, by alerting you to tread wear and alignment issues. And with a tread compound that resists distortion and wear, the Altimax RT43 is a long-lasting, dependable tire you can rely on.", brandName:"General", price:"135.99", year:"2011", model:"Audi", make:"A8 4.2 Quattro" },
  {name:"Altimax RT43", brand:"255/45R19XL", itemNum:"15502750001", desc:"With powerful all-season traction, built-in safety features, and a smooth, quiet ride, the General Altimax RT43 has everything you look for in a touring tire – and then some. This tire is packed with smart monitoring technology that helps keep you safe on the road, by alerting you to tread wear and alignment issues. And with a tread compound that resists distortion and wear, the Altimax RT43 is a long-lasting, dependable tire you can rely on.", brandName:"General", price:"150.99", year:"2011", model:"Audi", make:"A8 4.2 Quattro"},
  {name:"iMOVE GEN2 AS", brand:"235/45ZR18", itemNum:"93023", desc:"High performance all-season touring tires offer strong handling, exceptional all-season traction, and a plush ride – and often, a hefty price tag. But the Ironman iMove Gen 2 AS tire delivers all the pros without the sticker shock. The next generation of Ironman’s popular iMove tire delivers strong grip on wet and dry roads, responsive handling, a quiet ride, and durable, long-lasting construction. What more could you want?", brandName:"Ironman", price:"79.99", year:"2014", model:"Audi", make:"LA8 4.2 Quattro" }
  ])
